### ISSUE TITLE
HardwareRenderer.nSetStopped is now created in my app after using ANRSpy in app

### ISSUE THREAD

**Issue by Jamalzahid** [farimarwat/ANR-Spy#6]
`          Non-fatal Exception: V0.b: Method: nSetStopped is blocking main thread for at least 3200 ms
       at android.graphics.HardwareRenderer.nSetStopped(HardwareRenderer.java)
       at android.graphics.HardwareRenderer.setStopped(HardwareRenderer.java:498)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4279)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:780)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        `
        I never seen this issue in my app before using ANRSpy on google play console or firebase. It's increasing rapidly now
        
        
        Also this 
        
        `          Non-fatal Exception: V0.b: Method: transactNative is blocking main thread for at least 3200 ms
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:571)
       at android.view.IWindowSession$Stub$Proxy.getInTouchMode(IWindowSession.java:1729)
       at android.view.ViewRootImpl.isInTouchMode(ViewRootImpl.java:954)
       at android.view.View.isInTouchMode(View.java:15216)
       at mu0.b(chromium-SystemWebView.apk-default-463807403:1)
       at org.chromium.ui.base.ViewAndroidDelegate.hasFocus(chromium-SystemWebView.apk-default-463807403:2)
       at J.N.MAqmDh4t(chromium-SystemWebView.apk-default-463807403)
       at org.chromium.content.browser.framehost.NavigationControllerImpl.j(chromium-SystemWebView.apk-default-463807403:17)
       at org.chromium.android_webview.AwContents.w(chromium-SystemWebView.apk-default-463807403:47)
       at org.chromium.android_webview.AwContents.x(chromium-SystemWebView.apk-default-463807403:14)
       at com.android.webview.chromium.WebViewChromium.loadUrl(chromium-SystemWebView.apk-default-463807403:12)
       at android.webkit.WebView.loadUrl(WebView.java:743)
       at com.appchunks.backgroundvideorecorder.activities.PrivacyActivity.onCreate(PrivacyActivity.kt:151)
       at android.app.Activity.performCreate(Activity.java:8054)
       at android.app.Activity.performCreate(Activity.java:8034)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        `
        
        these both arise up after adding ANRSpy in my app before ANRSpy I never seen these two types of ANRs

**Comment by Jamalzahid** [comment]
Also 
`          Non-fatal Exception: V0.b: Method: transactNative is blocking main thread for at least 3200 ms
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:571)
       at android.view.IWindowSession$Stub$Proxy.getInTouchMode(IWindowSession.java:1729)
       at android.view.ViewRootImpl.isInTouchMode(ViewRootImpl.java:954)
       at android.view.View.isInTouchMode(View.java:15216)
       at mu0.b(chromium-SystemWebView.apk-default-463807403:1)
       at org.chromium.ui.base.ViewAndroidDelegate.hasFocus(chromium-SystemWebView.apk-default-463807403:2)
       at J.N.MAqmDh4t(chromium-SystemWebView.apk-default-463807403)
       at org.chromium.content.browser.framehost.NavigationControllerImpl.j(chromium-SystemWebView.apk-default-463807403:17)
       at org.chromium.android_webview.AwContents.w(chromium-SystemWebView.apk-default-463807403:47)
       at org.chromium.android_webview.AwContents.x(chromium-SystemWebView.apk-default-463807403:14)
       at com.android.webview.chromium.WebViewChromium.loadUrl(chromium-SystemWebView.apk-default-463807403:12)
       at android.webkit.WebView.loadUrl(WebView.java:743)
       at com.appchunks.backgroundvideorecorder.activities.PrivacyActivity.onCreate(PrivacyActivity.kt:151)
       at android.app.Activity.performCreate(Activity.java:8054)
       at android.app.Activity.performCreate(Activity.java:8034)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        `
        
        this type of ANR I never seen on console or firebase before using ANRSpy in app

**Comment by farimarwat** [comment]
Kindly read the docs carefully. there are not anrs. These are logs reported by ANRSpy because these functions are trying to approach the ANR limit which is 5 secs. Acoording to your ANRSpy configuration during building an instance, you set ANR limit to 3 seconds and also set an instance of firebase. so if you don't want to get such reports then do not build with firebase instance

**Comment by Jamalzahid** [comment]
Ok understood but After adding ANRSpy and setting time 3 seconds some ANRs still posting on console. I didn't understand why those are still on google play console. Those are from almost all versions of android. Could you please guide?
